class Product::Amazon < Product
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # 获取商品详情
  def get_content
    page = Nokogiri::HTML(http_get(link))
    self.info = page.css("#productDescription .content").to_s
    self.save
  end

  def link
    URI::encode(url || "http://www.amazon.cn/#{(name.blank? ? "-" : name ).gsub(" ", "-").gsub("/", "-")}/dp/#{url_key}/ref=")
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
