class Product::Dangdang < Product
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # 获取商品详情
  def get_content
    page = Nokogiri::HTML(http_get(link), nil, 'gbk')
    self.name = page.css(".head h1").text
    self.category = page.css(".breadcrumb a").map{ |a| a.text }.join(",")
    self.info = page.css("#detail_all").to_s
    self.count = page.css("#comm_num_down i").text
    self.score = page.css("#comm_num_up i").last.text.scan(%r|[\d\.]+|).first rescue nil
    self.save
  end

  def link
    "http://product.dangdang.com/#{url_key}.html"
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
