class Product::Gome < Product
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # 获取商品详情
  def get_content
    page = Nokogiri::HTML(http_get(link))
    self.category = page.css(".local a").map(&:text)[1, 2].join(',')
    self.image_url = page.css(".j-bpic-b").attr("gome-src").text
    self.save
    record_info Nokogiri::HTML(http_get(page.css("script")[-4].text.scan(/htmHref:\"(.+?)\"/).first.first)).css("table").to_s
  end

  def link
    "http://www.gome.com.cn/product/#{url_key}.html"
  end

  def purchase_link
    link
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
