class Product::Newegg < Product
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # 获取商品详情
  def get_content
    page = Nokogiri::HTML(http_get(link), nil, "GBK")
    self.name = page.css(".proHeader h1").text
    self.category = page.css("#crumb .inner").text.split(" > ")[1, 4].join(",")
    self.save
  end

  def link
    url
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
