class BargainsCategory < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # attr_accessible :bargain_id, :category_id

  # relationships .............................................................
  belongs_to :bargain
  belongs_to :caregory

  # validations ...............................................................
  # callbacks .................................................................
  after_save :update_bargain

  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private
  def update_bargain
    bargain.update(category_ids: ",#{bargain.bargains_categories.map(&:category_id).join(',')}" )
  end
end
