class Category < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  attr_accessible :name, :words

  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  def self.classify(category_array_str)
    result = []
    category_array_str.split("|").each do |category_str|
      category_str.split(",").reverse.each do |word|
        self.all.each do |category|
          result << category.id if category.words.to_s.split(",").index(word)
        end
      end
    end
    return result
  end

  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end