class Price < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  attr_accessible :value

  # relationships .............................................................
  belongs_to :product
  
  # validations ...............................................................
  validate :validate_too_frequent

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def validate_too_frequent
    # errors["created_at"] << ("update too frequent") if Time.now - product.updated_at < 1.hours 
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
