class ProductRoot < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  include Patcher

  # security (i.e. attr_accessible) ...........................................
  attr_accessible :url

  # relationships .............................................................
  has_many :product_lists

  # validations ...............................................................
  validates :url, :uniqueness => true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def get_lists
    Nokogiri::HTML(http_get(url)).css("#sortlist .item a").map{ |a| a.attr("href") }.each do |url|
      product_lists.create(url: url)
    end
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
