class ProductRoot::Dangdang < ProductRoot
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def get_lists
    page = Nokogiri::HTML(http_get(url),nil,'GBK')
    page.css(".col_4 h4 a")[0,28].each do |a|
      ProductList::Dangdang.create(url: a.attr("href"), url_key: a.attr("href").scan(%r|cid\d+|).first)
    end
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
  # private
end
