class ProductRoot::Newegg < ProductRoot
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def get_lists
    page = Nokogiri::HTML(http_get(url),nil,'GBK')
    page.css("dl").each_with_index do |dl, index|
      next unless [2, 3, 4, 5, 6, 7, 10, 12].index index
      dl.css("")

    end


    links = [] 
    page.css("#shopAllLinks td")[1].css("li li a").each{|a| links << a }
    page.css("#shopAllLinks td")[2].css("div").first.css("li li a").each{|a| links << a }
    links.each do |link|
      url = link.attr("href")
      ProductList::Amazon.create(url: url, url_key: get_key(url)) if get_key(url)
    end
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
  # private
  def get_key url
    keys = url.scan(%r|node=(\d+)|).first || url.scan(%r|\%3A(\d+)|).last || []
    keys.first
  end
end