class ProductRoot::Newegg < ProductRoot
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def get_lists
    page = Nokogiri::HTML(http_get(url),nil,'GBK')
    page.css("dl").each_with_index do |dl, index|
      next unless [2, 3, 4, 5, 6, 7, 10, 12].index index
      dl.css("em a").each do |a|
        ProductList::Newegg.create(url: a.attr("href"))
      end
    end
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
  # private
end
